// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sdmp/v1/envelope.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Well-known flag bits for Envelope.flags.
type EnvelopeFlag int32

const (
	EnvelopeFlag_ENVELOPE_FLAG_UNSPECIFIED EnvelopeFlag = 0
	// This message retracts a previously sent message (identified by thread_id).
	EnvelopeFlag_ENVELOPE_FLAG_RETRACTION EnvelopeFlag = 1
	// Sender requests a read receipt.
	EnvelopeFlag_ENVELOPE_FLAG_READ_RECEIPT_REQUESTED EnvelopeFlag = 2
	// Sender's domain uses mandatory key escrow (disclosed per protocol).
	EnvelopeFlag_ENVELOPE_FLAG_ESCROW_DISCLOSED EnvelopeFlag = 4
	// This is a reference message containing IDs of associated file transfers.
	EnvelopeFlag_ENVELOPE_FLAG_REFERENCE EnvelopeFlag = 8
)

// Enum value maps for EnvelopeFlag.
var (
	EnvelopeFlag_name = map[int32]string{
		0: "ENVELOPE_FLAG_UNSPECIFIED",
		1: "ENVELOPE_FLAG_RETRACTION",
		2: "ENVELOPE_FLAG_READ_RECEIPT_REQUESTED",
		4: "ENVELOPE_FLAG_ESCROW_DISCLOSED",
		8: "ENVELOPE_FLAG_REFERENCE",
	}
	EnvelopeFlag_value = map[string]int32{
		"ENVELOPE_FLAG_UNSPECIFIED":            0,
		"ENVELOPE_FLAG_RETRACTION":             1,
		"ENVELOPE_FLAG_READ_RECEIPT_REQUESTED": 2,
		"ENVELOPE_FLAG_ESCROW_DISCLOSED":       4,
		"ENVELOPE_FLAG_REFERENCE":              8,
	}
)

func (x EnvelopeFlag) Enum() *EnvelopeFlag {
	p := new(EnvelopeFlag)
	*p = x
	return p
}

func (x EnvelopeFlag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvelopeFlag) Descriptor() protoreflect.EnumDescriptor {
	return file_sdmp_v1_envelope_proto_enumTypes[0].Descriptor()
}

func (EnvelopeFlag) Type() protoreflect.EnumType {
	return &file_sdmp_v1_envelope_proto_enumTypes[0]
}

func (x EnvelopeFlag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvelopeFlag.Descriptor instead.
func (EnvelopeFlag) EnumDescriptor() ([]byte, []int) {
	return file_sdmp_v1_envelope_proto_rawDescGZIP(), []int{0}
}

// Envelope contains the protocol-defined metadata for a message.
// Servers operate only on envelopes — payloads are opaque encrypted bytes.
// The envelope is encrypted to the receiving domain's key; intermediate
// servers see only the destination domain.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Destination domain for routing.
	DestinationDomain string `protobuf:"bytes,1,opt,name=destination_domain,json=destinationDomain,proto3" json:"destination_domain,omitempty"`
	// Cryptographically bound sender identity (visible to destination domain only).
	Sender string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// Hashed recipient address — opaque to the receiving domain.
	RecipientHash []byte `protobuf:"bytes,3,opt,name=recipient_hash,json=recipientHash,proto3" json:"recipient_hash,omitempty"`
	// Globally unique, cryptographically random, protocol-generated.
	MessageId []byte `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Parent message ID for protocol-level threading. Empty if not a reply.
	ThreadId []byte `protobuf:"bytes,5,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	// Declared content type of the payload (hint only, client-validated).
	PayloadMimeType string `protobuf:"bytes,6,opt,name=payload_mime_type,json=payloadMimeType,proto3" json:"payload_mime_type,omitempty"`
	// Byte count of the encrypted payload.
	PayloadSize uint64 `protobuf:"varint,7,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	// Hash of the encrypted payload — integrity verification without decryption.
	PayloadHash []byte `protobuf:"bytes,8,opt,name=payload_hash,json=payloadHash,proto3" json:"payload_hash,omitempty"`
	// Sender-attested timestamp (Unix seconds).
	Timestamp int64 `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Per-message transit expiry (Unix seconds).
	TransitExpiry int64 `protobuf:"varint,10,opt,name=transit_expiry,json=transitExpiry,proto3" json:"transit_expiry,omitempty"`
	// Message flags.
	Flags uint32 `protobuf:"varint,11,opt,name=flags,proto3" json:"flags,omitempty"`
	// Signature over all preceding fields by the sender's signing key.
	EnvelopeSignature []byte `protobuf:"bytes,12,opt,name=envelope_signature,json=envelopeSignature,proto3" json:"envelope_signature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_sdmp_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_sdmp_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_sdmp_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetDestinationDomain() string {
	if x != nil {
		return x.DestinationDomain
	}
	return ""
}

func (x *Envelope) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Envelope) GetRecipientHash() []byte {
	if x != nil {
		return x.RecipientHash
	}
	return nil
}

func (x *Envelope) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *Envelope) GetThreadId() []byte {
	if x != nil {
		return x.ThreadId
	}
	return nil
}

func (x *Envelope) GetPayloadMimeType() string {
	if x != nil {
		return x.PayloadMimeType
	}
	return ""
}

func (x *Envelope) GetPayloadSize() uint64 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *Envelope) GetPayloadHash() []byte {
	if x != nil {
		return x.PayloadHash
	}
	return nil
}

func (x *Envelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Envelope) GetTransitExpiry() int64 {
	if x != nil {
		return x.TransitExpiry
	}
	return 0
}

func (x *Envelope) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Envelope) GetEnvelopeSignature() []byte {
	if x != nil {
		return x.EnvelopeSignature
	}
	return nil
}

var File_sdmp_v1_envelope_proto protoreflect.FileDescriptor

const file_sdmp_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x16sdmp/v1/envelope.proto\x12\asdmp.v1\"\xb0\x03\n" +
	"\bEnvelope\x12-\n" +
	"\x12destination_domain\x18\x01 \x01(\tR\x11destinationDomain\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12%\n" +
	"\x0erecipient_hash\x18\x03 \x01(\fR\rrecipientHash\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\fR\tmessageId\x12\x1b\n" +
	"\tthread_id\x18\x05 \x01(\fR\bthreadId\x12*\n" +
	"\x11payload_mime_type\x18\x06 \x01(\tR\x0fpayloadMimeType\x12!\n" +
	"\fpayload_size\x18\a \x01(\x04R\vpayloadSize\x12!\n" +
	"\fpayload_hash\x18\b \x01(\fR\vpayloadHash\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\x12%\n" +
	"\x0etransit_expiry\x18\n" +
	" \x01(\x03R\rtransitExpiry\x12\x14\n" +
	"\x05flags\x18\v \x01(\rR\x05flags\x12-\n" +
	"\x12envelope_signature\x18\f \x01(\fR\x11envelopeSignature*\xb6\x01\n" +
	"\fEnvelopeFlag\x12\x1d\n" +
	"\x19ENVELOPE_FLAG_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ENVELOPE_FLAG_RETRACTION\x10\x01\x12(\n" +
	"$ENVELOPE_FLAG_READ_RECEIPT_REQUESTED\x10\x02\x12\"\n" +
	"\x1eENVELOPE_FLAG_ESCROW_DISCLOSED\x10\x04\x12\x1b\n" +
	"\x17ENVELOPE_FLAG_REFERENCE\x10\bB*Z(github.com/infodancer/sdmp/proto/sdmp/v1b\x06proto3"

var (
	file_sdmp_v1_envelope_proto_rawDescOnce sync.Once
	file_sdmp_v1_envelope_proto_rawDescData []byte
)

func file_sdmp_v1_envelope_proto_rawDescGZIP() []byte {
	file_sdmp_v1_envelope_proto_rawDescOnce.Do(func() {
		file_sdmp_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdmp_v1_envelope_proto_rawDesc), len(file_sdmp_v1_envelope_proto_rawDesc)))
	})
	return file_sdmp_v1_envelope_proto_rawDescData
}

var file_sdmp_v1_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdmp_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdmp_v1_envelope_proto_goTypes = []any{
	(EnvelopeFlag)(0), // 0: sdmp.v1.EnvelopeFlag
	(*Envelope)(nil),  // 1: sdmp.v1.Envelope
}
var file_sdmp_v1_envelope_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdmp_v1_envelope_proto_init() }
func file_sdmp_v1_envelope_proto_init() {
	if File_sdmp_v1_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdmp_v1_envelope_proto_rawDesc), len(file_sdmp_v1_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdmp_v1_envelope_proto_goTypes,
		DependencyIndexes: file_sdmp_v1_envelope_proto_depIdxs,
		EnumInfos:         file_sdmp_v1_envelope_proto_enumTypes,
		MessageInfos:      file_sdmp_v1_envelope_proto_msgTypes,
	}.Build()
	File_sdmp_v1_envelope_proto = out.File
	file_sdmp_v1_envelope_proto_goTypes = nil
	file_sdmp_v1_envelope_proto_depIdxs = nil
}
