// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: sdmp/v1/fetch.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FetchService_FetchMessage_FullMethodName       = "/sdmp.v1.FetchService/FetchMessage"
	FetchService_BatchFetchMessages_FullMethodName = "/sdmp.v1.FetchService/BatchFetchMessages"
)

// FetchServiceClient is the client API for FetchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FetchService handles message retrieval between domains.
// Authenticated via mTLS with domain signing keys as client certificates.
type FetchServiceClient interface {
	// FetchMessage retrieves a message by ID. The response contains the
	// envelope and encrypted payload. The caller must possess the message ID
	// (capability token) and authenticate as the recipient's domain.
	FetchMessage(ctx context.Context, in *FetchMessageRequest, opts ...grpc.CallOption) (*FetchMessageResponse, error)
	// BatchFetchMessages retrieves multiple messages in a single call.
	// Useful for initial sync or gateway bulk transfer.
	BatchFetchMessages(ctx context.Context, in *BatchFetchMessagesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchMessageResponse], error)
}

type fetchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFetchServiceClient(cc grpc.ClientConnInterface) FetchServiceClient {
	return &fetchServiceClient{cc}
}

func (c *fetchServiceClient) FetchMessage(ctx context.Context, in *FetchMessageRequest, opts ...grpc.CallOption) (*FetchMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchMessageResponse)
	err := c.cc.Invoke(ctx, FetchService_FetchMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fetchServiceClient) BatchFetchMessages(ctx context.Context, in *BatchFetchMessagesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FetchMessageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FetchService_ServiceDesc.Streams[0], FetchService_BatchFetchMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchFetchMessagesRequest, FetchMessageResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FetchService_BatchFetchMessagesClient = grpc.ServerStreamingClient[FetchMessageResponse]

// FetchServiceServer is the server API for FetchService service.
// All implementations must embed UnimplementedFetchServiceServer
// for forward compatibility.
//
// FetchService handles message retrieval between domains.
// Authenticated via mTLS with domain signing keys as client certificates.
type FetchServiceServer interface {
	// FetchMessage retrieves a message by ID. The response contains the
	// envelope and encrypted payload. The caller must possess the message ID
	// (capability token) and authenticate as the recipient's domain.
	FetchMessage(context.Context, *FetchMessageRequest) (*FetchMessageResponse, error)
	// BatchFetchMessages retrieves multiple messages in a single call.
	// Useful for initial sync or gateway bulk transfer.
	BatchFetchMessages(*BatchFetchMessagesRequest, grpc.ServerStreamingServer[FetchMessageResponse]) error
	mustEmbedUnimplementedFetchServiceServer()
}

// UnimplementedFetchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFetchServiceServer struct{}

func (UnimplementedFetchServiceServer) FetchMessage(context.Context, *FetchMessageRequest) (*FetchMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchMessage not implemented")
}
func (UnimplementedFetchServiceServer) BatchFetchMessages(*BatchFetchMessagesRequest, grpc.ServerStreamingServer[FetchMessageResponse]) error {
	return status.Error(codes.Unimplemented, "method BatchFetchMessages not implemented")
}
func (UnimplementedFetchServiceServer) mustEmbedUnimplementedFetchServiceServer() {}
func (UnimplementedFetchServiceServer) testEmbeddedByValue()                      {}

// UnsafeFetchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FetchServiceServer will
// result in compilation errors.
type UnsafeFetchServiceServer interface {
	mustEmbedUnimplementedFetchServiceServer()
}

func RegisterFetchServiceServer(s grpc.ServiceRegistrar, srv FetchServiceServer) {
	// If the following call panics, it indicates UnimplementedFetchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FetchService_ServiceDesc, srv)
}

func _FetchService_FetchMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FetchServiceServer).FetchMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FetchService_FetchMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FetchServiceServer).FetchMessage(ctx, req.(*FetchMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FetchService_BatchFetchMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BatchFetchMessagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FetchServiceServer).BatchFetchMessages(m, &grpc.GenericServerStream[BatchFetchMessagesRequest, FetchMessageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FetchService_BatchFetchMessagesServer = grpc.ServerStreamingServer[FetchMessageResponse]

// FetchService_ServiceDesc is the grpc.ServiceDesc for FetchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FetchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sdmp.v1.FetchService",
	HandlerType: (*FetchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchMessage",
			Handler:    _FetchService_FetchMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BatchFetchMessages",
			Handler:       _FetchService_BatchFetchMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sdmp/v1/fetch.proto",
}
