// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sdmp/v1/fetch.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message ID to retrieve (capability token).
	MessageId     []byte `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMessageRequest) Reset() {
	*x = FetchMessageRequest{}
	mi := &file_sdmp_v1_fetch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMessageRequest) ProtoMessage() {}

func (x *FetchMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdmp_v1_fetch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMessageRequest.ProtoReflect.Descriptor instead.
func (*FetchMessageRequest) Descriptor() ([]byte, []int) {
	return file_sdmp_v1_fetch_proto_rawDescGZIP(), []int{0}
}

func (x *FetchMessageRequest) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

type FetchMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message envelope (decryptable by the recipient's domain).
	Envelope *Envelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// The encrypted payload (decryptable only by the recipient's user key).
	EncryptedPayload []byte `protobuf:"bytes,2,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FetchMessageResponse) Reset() {
	*x = FetchMessageResponse{}
	mi := &file_sdmp_v1_fetch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMessageResponse) ProtoMessage() {}

func (x *FetchMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdmp_v1_fetch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMessageResponse.ProtoReflect.Descriptor instead.
func (*FetchMessageResponse) Descriptor() ([]byte, []int) {
	return file_sdmp_v1_fetch_proto_rawDescGZIP(), []int{1}
}

func (x *FetchMessageResponse) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *FetchMessageResponse) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

type BatchFetchMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of message IDs to retrieve.
	MessageIds    [][]byte `protobuf:"bytes,1,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchFetchMessagesRequest) Reset() {
	*x = BatchFetchMessagesRequest{}
	mi := &file_sdmp_v1_fetch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchFetchMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchFetchMessagesRequest) ProtoMessage() {}

func (x *BatchFetchMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdmp_v1_fetch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchFetchMessagesRequest.ProtoReflect.Descriptor instead.
func (*BatchFetchMessagesRequest) Descriptor() ([]byte, []int) {
	return file_sdmp_v1_fetch_proto_rawDescGZIP(), []int{2}
}

func (x *BatchFetchMessagesRequest) GetMessageIds() [][]byte {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

var File_sdmp_v1_fetch_proto protoreflect.FileDescriptor

const file_sdmp_v1_fetch_proto_rawDesc = "" +
	"\n" +
	"\x13sdmp/v1/fetch.proto\x12\asdmp.v1\x1a\x16sdmp/v1/envelope.proto\"4\n" +
	"\x13FetchMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\"r\n" +
	"\x14FetchMessageResponse\x12-\n" +
	"\benvelope\x18\x01 \x01(\v2\x11.sdmp.v1.EnvelopeR\benvelope\x12+\n" +
	"\x11encrypted_payload\x18\x02 \x01(\fR\x10encryptedPayload\"<\n" +
	"\x19BatchFetchMessagesRequest\x12\x1f\n" +
	"\vmessage_ids\x18\x01 \x03(\fR\n" +
	"messageIds2\xb6\x01\n" +
	"\fFetchService\x12K\n" +
	"\fFetchMessage\x12\x1c.sdmp.v1.FetchMessageRequest\x1a\x1d.sdmp.v1.FetchMessageResponse\x12Y\n" +
	"\x12BatchFetchMessages\x12\".sdmp.v1.BatchFetchMessagesRequest\x1a\x1d.sdmp.v1.FetchMessageResponse0\x01B*Z(github.com/infodancer/sdmp/proto/sdmp/v1b\x06proto3"

var (
	file_sdmp_v1_fetch_proto_rawDescOnce sync.Once
	file_sdmp_v1_fetch_proto_rawDescData []byte
)

func file_sdmp_v1_fetch_proto_rawDescGZIP() []byte {
	file_sdmp_v1_fetch_proto_rawDescOnce.Do(func() {
		file_sdmp_v1_fetch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdmp_v1_fetch_proto_rawDesc), len(file_sdmp_v1_fetch_proto_rawDesc)))
	})
	return file_sdmp_v1_fetch_proto_rawDescData
}

var file_sdmp_v1_fetch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sdmp_v1_fetch_proto_goTypes = []any{
	(*FetchMessageRequest)(nil),       // 0: sdmp.v1.FetchMessageRequest
	(*FetchMessageResponse)(nil),      // 1: sdmp.v1.FetchMessageResponse
	(*BatchFetchMessagesRequest)(nil), // 2: sdmp.v1.BatchFetchMessagesRequest
	(*Envelope)(nil),                  // 3: sdmp.v1.Envelope
}
var file_sdmp_v1_fetch_proto_depIdxs = []int32{
	3, // 0: sdmp.v1.FetchMessageResponse.envelope:type_name -> sdmp.v1.Envelope
	0, // 1: sdmp.v1.FetchService.FetchMessage:input_type -> sdmp.v1.FetchMessageRequest
	2, // 2: sdmp.v1.FetchService.BatchFetchMessages:input_type -> sdmp.v1.BatchFetchMessagesRequest
	1, // 3: sdmp.v1.FetchService.FetchMessage:output_type -> sdmp.v1.FetchMessageResponse
	1, // 4: sdmp.v1.FetchService.BatchFetchMessages:output_type -> sdmp.v1.FetchMessageResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sdmp_v1_fetch_proto_init() }
func file_sdmp_v1_fetch_proto_init() {
	if File_sdmp_v1_fetch_proto != nil {
		return
	}
	file_sdmp_v1_envelope_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdmp_v1_fetch_proto_rawDesc), len(file_sdmp_v1_fetch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdmp_v1_fetch_proto_goTypes,
		DependencyIndexes: file_sdmp_v1_fetch_proto_depIdxs,
		MessageInfos:      file_sdmp_v1_fetch_proto_msgTypes,
	}.Build()
	File_sdmp_v1_fetch_proto = out.File
	file_sdmp_v1_fetch_proto_goTypes = nil
	file_sdmp_v1_fetch_proto_depIdxs = nil
}
