// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: sdmp/v1/keys.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyService_GetDomainKey_FullMethodName = "/sdmp.v1.KeyService/GetDomainKey"
	KeyService_GetUserKey_FullMethodName   = "/sdmp.v1.KeyService/GetUserKey"
)

// KeyServiceClient is the client API for KeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KeyService handles domain and user key publication and discovery.
// Authenticated via mTLS with domain signing keys.
type KeyServiceClient interface {
	// GetDomainKey retrieves a domain's current signing key and metadata.
	GetDomainKey(ctx context.Context, in *GetDomainKeyRequest, opts ...grpc.CallOption) (*DomainKeyResponse, error)
	// GetUserKey retrieves a user's published key record, signed by their domain.
	GetUserKey(ctx context.Context, in *GetUserKeyRequest, opts ...grpc.CallOption) (*UserKeyResponse, error)
}

type keyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyServiceClient(cc grpc.ClientConnInterface) KeyServiceClient {
	return &keyServiceClient{cc}
}

func (c *keyServiceClient) GetDomainKey(ctx context.Context, in *GetDomainKeyRequest, opts ...grpc.CallOption) (*DomainKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainKeyResponse)
	err := c.cc.Invoke(ctx, KeyService_GetDomainKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) GetUserKey(ctx context.Context, in *GetUserKeyRequest, opts ...grpc.CallOption) (*UserKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserKeyResponse)
	err := c.cc.Invoke(ctx, KeyService_GetUserKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyServiceServer is the server API for KeyService service.
// All implementations must embed UnimplementedKeyServiceServer
// for forward compatibility.
//
// KeyService handles domain and user key publication and discovery.
// Authenticated via mTLS with domain signing keys.
type KeyServiceServer interface {
	// GetDomainKey retrieves a domain's current signing key and metadata.
	GetDomainKey(context.Context, *GetDomainKeyRequest) (*DomainKeyResponse, error)
	// GetUserKey retrieves a user's published key record, signed by their domain.
	GetUserKey(context.Context, *GetUserKeyRequest) (*UserKeyResponse, error)
	mustEmbedUnimplementedKeyServiceServer()
}

// UnimplementedKeyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyServiceServer struct{}

func (UnimplementedKeyServiceServer) GetDomainKey(context.Context, *GetDomainKeyRequest) (*DomainKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDomainKey not implemented")
}
func (UnimplementedKeyServiceServer) GetUserKey(context.Context, *GetUserKeyRequest) (*UserKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserKey not implemented")
}
func (UnimplementedKeyServiceServer) mustEmbedUnimplementedKeyServiceServer() {}
func (UnimplementedKeyServiceServer) testEmbeddedByValue()                    {}

// UnsafeKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyServiceServer will
// result in compilation errors.
type UnsafeKeyServiceServer interface {
	mustEmbedUnimplementedKeyServiceServer()
}

func RegisterKeyServiceServer(s grpc.ServiceRegistrar, srv KeyServiceServer) {
	// If the following call panics, it indicates UnimplementedKeyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyService_ServiceDesc, srv)
}

func _KeyService_GetDomainKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDomainKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).GetDomainKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_GetDomainKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).GetDomainKey(ctx, req.(*GetDomainKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_GetUserKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).GetUserKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyService_GetUserKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).GetUserKey(ctx, req.(*GetUserKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyService_ServiceDesc is the grpc.ServiceDesc for KeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sdmp.v1.KeyService",
	HandlerType: (*KeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDomainKey",
			Handler:    _KeyService_GetDomainKey_Handler,
		},
		{
			MethodName: "GetUserKey",
			Handler:    _KeyService_GetUserKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdmp/v1/keys.proto",
}
