// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sdmp/v1/keys.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDomainKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The domain to look up.
	Domain        string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDomainKeyRequest) Reset() {
	*x = GetDomainKeyRequest{}
	mi := &file_sdmp_v1_keys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDomainKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDomainKeyRequest) ProtoMessage() {}

func (x *GetDomainKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdmp_v1_keys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDomainKeyRequest.ProtoReflect.Descriptor instead.
func (*GetDomainKeyRequest) Descriptor() ([]byte, []int) {
	return file_sdmp_v1_keys_proto_rawDescGZIP(), []int{0}
}

func (x *GetDomainKeyRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type DomainKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Domain name.
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// Public key algorithm (e.g. "Ed25519", "X25519").
	Algorithm string `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// Public key material.
	PublicKey []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Key fingerprint (hash of public key material).
	Fingerprint []byte `protobuf:"bytes,4,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// Validity period start (Unix seconds).
	ValidFrom int64 `protobuf:"varint,5,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	// Validity period end (Unix seconds).
	ValidUntil int64 `protobuf:"varint,6,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	// Whether this domain uses mandatory key escrow.
	EscrowMandatory bool `protobuf:"varint,7,opt,name=escrow_mandatory,json=escrowMandatory,proto3" json:"escrow_mandatory,omitempty"`
	// Signature by the domain's signing key over the above fields.
	Signature     []byte `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainKeyResponse) Reset() {
	*x = DomainKeyResponse{}
	mi := &file_sdmp_v1_keys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainKeyResponse) ProtoMessage() {}

func (x *DomainKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdmp_v1_keys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainKeyResponse.ProtoReflect.Descriptor instead.
func (*DomainKeyResponse) Descriptor() ([]byte, []int) {
	return file_sdmp_v1_keys_proto_rawDescGZIP(), []int{1}
}

func (x *DomainKeyResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainKeyResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *DomainKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *DomainKeyResponse) GetFingerprint() []byte {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *DomainKeyResponse) GetValidFrom() int64 {
	if x != nil {
		return x.ValidFrom
	}
	return 0
}

func (x *DomainKeyResponse) GetValidUntil() int64 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

func (x *DomainKeyResponse) GetEscrowMandatory() bool {
	if x != nil {
		return x.EscrowMandatory
	}
	return false
}

func (x *DomainKeyResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type GetUserKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's address (e.g. "alice@example.com").
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserKeyRequest) Reset() {
	*x = GetUserKeyRequest{}
	mi := &file_sdmp_v1_keys_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserKeyRequest) ProtoMessage() {}

func (x *GetUserKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdmp_v1_keys_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserKeyRequest.ProtoReflect.Descriptor instead.
func (*GetUserKeyRequest) Descriptor() ([]byte, []int) {
	return file_sdmp_v1_keys_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserKeyRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UserKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User address.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Public key algorithm.
	Algorithm string `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// Public key material.
	PublicKey []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Key fingerprint.
	Fingerprint []byte `protobuf:"bytes,4,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// Key creation timestamp (Unix seconds).
	Created int64 `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	// Validity period start (Unix seconds).
	ValidFrom int64 `protobuf:"varint,6,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	// Validity period end (Unix seconds).
	ValidUntil int64 `protobuf:"varint,7,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	// Whether the key is revoked.
	Revoked bool `protobuf:"varint,8,opt,name=revoked,proto3" json:"revoked,omitempty"`
	// Whether the key is escrowed by the domain.
	Escrowed bool `protobuf:"varint,9,opt,name=escrowed,proto3" json:"escrowed,omitempty"`
	// Domain's signature over all preceding fields.
	DomainSignature []byte `protobuf:"bytes,10,opt,name=domain_signature,json=domainSignature,proto3" json:"domain_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserKeyResponse) Reset() {
	*x = UserKeyResponse{}
	mi := &file_sdmp_v1_keys_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserKeyResponse) ProtoMessage() {}

func (x *UserKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdmp_v1_keys_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserKeyResponse.ProtoReflect.Descriptor instead.
func (*UserKeyResponse) Descriptor() ([]byte, []int) {
	return file_sdmp_v1_keys_proto_rawDescGZIP(), []int{3}
}

func (x *UserKeyResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserKeyResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *UserKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *UserKeyResponse) GetFingerprint() []byte {
	if x != nil {
		return x.Fingerprint
	}
	return nil
}

func (x *UserKeyResponse) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *UserKeyResponse) GetValidFrom() int64 {
	if x != nil {
		return x.ValidFrom
	}
	return 0
}

func (x *UserKeyResponse) GetValidUntil() int64 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

func (x *UserKeyResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *UserKeyResponse) GetEscrowed() bool {
	if x != nil {
		return x.Escrowed
	}
	return false
}

func (x *UserKeyResponse) GetDomainSignature() []byte {
	if x != nil {
		return x.DomainSignature
	}
	return nil
}

var File_sdmp_v1_keys_proto protoreflect.FileDescriptor

const file_sdmp_v1_keys_proto_rawDesc = "" +
	"\n" +
	"\x12sdmp/v1/keys.proto\x12\asdmp.v1\"-\n" +
	"\x13GetDomainKeyRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"\x93\x02\n" +
	"\x11DomainKeyResponse\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12 \n" +
	"\vfingerprint\x18\x04 \x01(\fR\vfingerprint\x12\x1d\n" +
	"\n" +
	"valid_from\x18\x05 \x01(\x03R\tvalidFrom\x12\x1f\n" +
	"\vvalid_until\x18\x06 \x01(\x03R\n" +
	"validUntil\x12)\n" +
	"\x10escrow_mandatory\x18\a \x01(\bR\x0fescrowMandatory\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\"-\n" +
	"\x11GetUserKeyRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\xc5\x02\n" +
	"\x0fUserKeyResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12 \n" +
	"\vfingerprint\x18\x04 \x01(\fR\vfingerprint\x12\x18\n" +
	"\acreated\x18\x05 \x01(\x03R\acreated\x12\x1d\n" +
	"\n" +
	"valid_from\x18\x06 \x01(\x03R\tvalidFrom\x12\x1f\n" +
	"\vvalid_until\x18\a \x01(\x03R\n" +
	"validUntil\x12\x18\n" +
	"\arevoked\x18\b \x01(\bR\arevoked\x12\x1a\n" +
	"\bescrowed\x18\t \x01(\bR\bescrowed\x12)\n" +
	"\x10domain_signature\x18\n" +
	" \x01(\fR\x0fdomainSignature2\x9a\x01\n" +
	"\n" +
	"KeyService\x12H\n" +
	"\fGetDomainKey\x12\x1c.sdmp.v1.GetDomainKeyRequest\x1a\x1a.sdmp.v1.DomainKeyResponse\x12B\n" +
	"\n" +
	"GetUserKey\x12\x1a.sdmp.v1.GetUserKeyRequest\x1a\x18.sdmp.v1.UserKeyResponseB*Z(github.com/infodancer/sdmp/proto/sdmp/v1b\x06proto3"

var (
	file_sdmp_v1_keys_proto_rawDescOnce sync.Once
	file_sdmp_v1_keys_proto_rawDescData []byte
)

func file_sdmp_v1_keys_proto_rawDescGZIP() []byte {
	file_sdmp_v1_keys_proto_rawDescOnce.Do(func() {
		file_sdmp_v1_keys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdmp_v1_keys_proto_rawDesc), len(file_sdmp_v1_keys_proto_rawDesc)))
	})
	return file_sdmp_v1_keys_proto_rawDescData
}

var file_sdmp_v1_keys_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sdmp_v1_keys_proto_goTypes = []any{
	(*GetDomainKeyRequest)(nil), // 0: sdmp.v1.GetDomainKeyRequest
	(*DomainKeyResponse)(nil),   // 1: sdmp.v1.DomainKeyResponse
	(*GetUserKeyRequest)(nil),   // 2: sdmp.v1.GetUserKeyRequest
	(*UserKeyResponse)(nil),     // 3: sdmp.v1.UserKeyResponse
}
var file_sdmp_v1_keys_proto_depIdxs = []int32{
	0, // 0: sdmp.v1.KeyService.GetDomainKey:input_type -> sdmp.v1.GetDomainKeyRequest
	2, // 1: sdmp.v1.KeyService.GetUserKey:input_type -> sdmp.v1.GetUserKeyRequest
	1, // 2: sdmp.v1.KeyService.GetDomainKey:output_type -> sdmp.v1.DomainKeyResponse
	3, // 3: sdmp.v1.KeyService.GetUserKey:output_type -> sdmp.v1.UserKeyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdmp_v1_keys_proto_init() }
func file_sdmp_v1_keys_proto_init() {
	if File_sdmp_v1_keys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdmp_v1_keys_proto_rawDesc), len(file_sdmp_v1_keys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdmp_v1_keys_proto_goTypes,
		DependencyIndexes: file_sdmp_v1_keys_proto_depIdxs,
		MessageInfos:      file_sdmp_v1_keys_proto_msgTypes,
	}.Build()
	File_sdmp_v1_keys_proto = out.File
	file_sdmp_v1_keys_proto_goTypes = nil
	file_sdmp_v1_keys_proto_depIdxs = nil
}
