// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sdmp/v1/notification.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Notification is a fire-and-forget UDP packet sent from a sending domain
// to a receiving domain to signal that a message is available for retrieval.
//
// Encrypted to the receiving domain's public key before transmission.
// The receiving domain provides NO response — silence is the only answer.
// This prevents address harvesting, infrastructure mapping, and backscatter.
type Notification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Globally unique, cryptographically random message identifier.
	// Functions as a capability token for fetching the encrypted payload.
	MessageId []byte `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Domain name of the sender (e.g. "example.com").
	SenderDomain string `protobuf:"bytes,2,opt,name=sender_domain,json=senderDomain,proto3" json:"sender_domain,omitempty"`
	// Opaque hash identifying the recipient. Derived from sender/recipient
	// key material via KDF. The receiving domain cannot map this to a user
	// account without the recipient's cooperation.
	RecipientHash []byte `protobuf:"bytes,3,opt,name=recipient_hash,json=recipientHash,proto3" json:"recipient_hash,omitempty"`
	// Sender-attested timestamp (Unix seconds).
	Timestamp int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Transit expiry (Unix seconds). After this time, the sender will
	// delete the message from transit storage. No retransmission after expiry.
	Expiry int64 `protobuf:"varint,5,opt,name=expiry,proto3" json:"expiry,omitempty"`
	// Declared content type hint (e.g. "message/822", "application/octet-stream").
	// Client-validated, not protocol-verified. Allows recipient server to make
	// pull/discard decisions without fetching.
	MimeTypeHint string `protobuf:"bytes,6,opt,name=mime_type_hint,json=mimeTypeHint,proto3" json:"mime_type_hint,omitempty"`
	// Byte count of the encrypted payload.
	PayloadSize uint64 `protobuf:"varint,7,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	// Signature over all preceding fields by the sender domain's signing key.
	Signature     []byte `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_sdmp_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_sdmp_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_sdmp_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *Notification) GetSenderDomain() string {
	if x != nil {
		return x.SenderDomain
	}
	return ""
}

func (x *Notification) GetRecipientHash() []byte {
	if x != nil {
		return x.RecipientHash
	}
	return nil
}

func (x *Notification) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Notification) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *Notification) GetMimeTypeHint() string {
	if x != nil {
		return x.MimeTypeHint
	}
	return ""
}

func (x *Notification) GetPayloadSize() uint64 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *Notification) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// EncryptedNotification is the wire format for a UDP notification packet.
// The inner notification is serialized and encrypted to the receiving
// domain's public key. A network observer sees only the destination
// domain and an opaque encrypted blob.
type EncryptedNotification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol version for forward compatibility.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Destination domain (the only field visible to network observers
	// and intermediate infrastructure).
	DestinationDomain string `protobuf:"bytes,2,opt,name=destination_domain,json=destinationDomain,proto3" json:"destination_domain,omitempty"`
	// The Notification message, serialized and encrypted to the
	// destination domain's public key.
	EncryptedPayload []byte `protobuf:"bytes,3,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	// Nonce used for encryption.
	Nonce         []byte `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedNotification) Reset() {
	*x = EncryptedNotification{}
	mi := &file_sdmp_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedNotification) ProtoMessage() {}

func (x *EncryptedNotification) ProtoReflect() protoreflect.Message {
	mi := &file_sdmp_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedNotification.ProtoReflect.Descriptor instead.
func (*EncryptedNotification) Descriptor() ([]byte, []int) {
	return file_sdmp_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptedNotification) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EncryptedNotification) GetDestinationDomain() string {
	if x != nil {
		return x.DestinationDomain
	}
	return ""
}

func (x *EncryptedNotification) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *EncryptedNotification) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

var File_sdmp_v1_notification_proto protoreflect.FileDescriptor

const file_sdmp_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\x1asdmp/v1/notification.proto\x12\asdmp.v1\"\x96\x02\n" +
	"\fNotification\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12#\n" +
	"\rsender_domain\x18\x02 \x01(\tR\fsenderDomain\x12%\n" +
	"\x0erecipient_hash\x18\x03 \x01(\fR\rrecipientHash\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06expiry\x18\x05 \x01(\x03R\x06expiry\x12$\n" +
	"\x0emime_type_hint\x18\x06 \x01(\tR\fmimeTypeHint\x12!\n" +
	"\fpayload_size\x18\a \x01(\x04R\vpayloadSize\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\"\xa3\x01\n" +
	"\x15EncryptedNotification\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12-\n" +
	"\x12destination_domain\x18\x02 \x01(\tR\x11destinationDomain\x12+\n" +
	"\x11encrypted_payload\x18\x03 \x01(\fR\x10encryptedPayload\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonceB*Z(github.com/infodancer/sdmp/proto/sdmp/v1b\x06proto3"

var (
	file_sdmp_v1_notification_proto_rawDescOnce sync.Once
	file_sdmp_v1_notification_proto_rawDescData []byte
)

func file_sdmp_v1_notification_proto_rawDescGZIP() []byte {
	file_sdmp_v1_notification_proto_rawDescOnce.Do(func() {
		file_sdmp_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdmp_v1_notification_proto_rawDesc), len(file_sdmp_v1_notification_proto_rawDesc)))
	})
	return file_sdmp_v1_notification_proto_rawDescData
}

var file_sdmp_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sdmp_v1_notification_proto_goTypes = []any{
	(*Notification)(nil),          // 0: sdmp.v1.Notification
	(*EncryptedNotification)(nil), // 1: sdmp.v1.EncryptedNotification
}
var file_sdmp_v1_notification_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdmp_v1_notification_proto_init() }
func file_sdmp_v1_notification_proto_init() {
	if File_sdmp_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdmp_v1_notification_proto_rawDesc), len(file_sdmp_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdmp_v1_notification_proto_goTypes,
		DependencyIndexes: file_sdmp_v1_notification_proto_depIdxs,
		MessageInfos:      file_sdmp_v1_notification_proto_msgTypes,
	}.Build()
	File_sdmp_v1_notification_proto = out.File
	file_sdmp_v1_notification_proto_goTypes = nil
	file_sdmp_v1_notification_proto_depIdxs = nil
}
