// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: sdmp/v1/transfer.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransferService_AcceptResponsibility_FullMethodName = "/sdmp.v1.TransferService/AcceptResponsibility"
)

// TransferServiceClient is the client API for TransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TransferService handles responsibility transfer between domains
// and gateways. When a gateway accepts a message, it assumes notification
// responsibility. The original sender's obligation ends.
type TransferServiceClient interface {
	// AcceptResponsibility signals that this server has accepted notification
	// responsibility for a message. Returns a signed receipt that the
	// original sender can verify and use to purge from transit storage.
	AcceptResponsibility(ctx context.Context, in *AcceptResponsibilityRequest, opts ...grpc.CallOption) (*AcceptResponsibilityResponse, error)
}

type transferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransferServiceClient(cc grpc.ClientConnInterface) TransferServiceClient {
	return &transferServiceClient{cc}
}

func (c *transferServiceClient) AcceptResponsibility(ctx context.Context, in *AcceptResponsibilityRequest, opts ...grpc.CallOption) (*AcceptResponsibilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptResponsibilityResponse)
	err := c.cc.Invoke(ctx, TransferService_AcceptResponsibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransferServiceServer is the server API for TransferService service.
// All implementations must embed UnimplementedTransferServiceServer
// for forward compatibility.
//
// TransferService handles responsibility transfer between domains
// and gateways. When a gateway accepts a message, it assumes notification
// responsibility. The original sender's obligation ends.
type TransferServiceServer interface {
	// AcceptResponsibility signals that this server has accepted notification
	// responsibility for a message. Returns a signed receipt that the
	// original sender can verify and use to purge from transit storage.
	AcceptResponsibility(context.Context, *AcceptResponsibilityRequest) (*AcceptResponsibilityResponse, error)
	mustEmbedUnimplementedTransferServiceServer()
}

// UnimplementedTransferServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransferServiceServer struct{}

func (UnimplementedTransferServiceServer) AcceptResponsibility(context.Context, *AcceptResponsibilityRequest) (*AcceptResponsibilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptResponsibility not implemented")
}
func (UnimplementedTransferServiceServer) mustEmbedUnimplementedTransferServiceServer() {}
func (UnimplementedTransferServiceServer) testEmbeddedByValue()                         {}

// UnsafeTransferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransferServiceServer will
// result in compilation errors.
type UnsafeTransferServiceServer interface {
	mustEmbedUnimplementedTransferServiceServer()
}

func RegisterTransferServiceServer(s grpc.ServiceRegistrar, srv TransferServiceServer) {
	// If the following call panics, it indicates UnimplementedTransferServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransferService_ServiceDesc, srv)
}

func _TransferService_AcceptResponsibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptResponsibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).AcceptResponsibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_AcceptResponsibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).AcceptResponsibility(ctx, req.(*AcceptResponsibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransferService_ServiceDesc is the grpc.ServiceDesc for TransferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sdmp.v1.TransferService",
	HandlerType: (*TransferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcceptResponsibility",
			Handler:    _TransferService_AcceptResponsibility_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdmp/v1/transfer.proto",
}
