// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sdmp/v1/transfer.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcceptResponsibilityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message ID being accepted.
	MessageId []byte `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// The recipient domain this gateway is accepting responsibility for.
	RecipientDomain string `protobuf:"bytes,2,opt,name=recipient_domain,json=recipientDomain,proto3" json:"recipient_domain,omitempty"`
	// The gateway domain accepting responsibility.
	GatewayDomain string `protobuf:"bytes,3,opt,name=gateway_domain,json=gatewayDomain,proto3" json:"gateway_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptResponsibilityRequest) Reset() {
	*x = AcceptResponsibilityRequest{}
	mi := &file_sdmp_v1_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResponsibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponsibilityRequest) ProtoMessage() {}

func (x *AcceptResponsibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdmp_v1_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponsibilityRequest.ProtoReflect.Descriptor instead.
func (*AcceptResponsibilityRequest) Descriptor() ([]byte, []int) {
	return file_sdmp_v1_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *AcceptResponsibilityRequest) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *AcceptResponsibilityRequest) GetRecipientDomain() string {
	if x != nil {
		return x.RecipientDomain
	}
	return ""
}

func (x *AcceptResponsibilityRequest) GetGatewayDomain() string {
	if x != nil {
		return x.GatewayDomain
	}
	return ""
}

type AcceptResponsibilityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message ID acknowledged.
	MessageId []byte `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// The expiry the gateway will honor (may differ from original).
	// The recipient domain now has visibility into the gateway's delivery window.
	GatewayExpiry int64 `protobuf:"varint,2,opt,name=gateway_expiry,json=gatewayExpiry,proto3" json:"gateway_expiry,omitempty"`
	// Signed receipt: gateway's signature over message_id + recipient_domain
	// + gateway_domain + gateway_expiry. Original sender can verify and purge.
	ReceiptSignature []byte `protobuf:"bytes,3,opt,name=receipt_signature,json=receiptSignature,proto3" json:"receipt_signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AcceptResponsibilityResponse) Reset() {
	*x = AcceptResponsibilityResponse{}
	mi := &file_sdmp_v1_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptResponsibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponsibilityResponse) ProtoMessage() {}

func (x *AcceptResponsibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdmp_v1_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponsibilityResponse.ProtoReflect.Descriptor instead.
func (*AcceptResponsibilityResponse) Descriptor() ([]byte, []int) {
	return file_sdmp_v1_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *AcceptResponsibilityResponse) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *AcceptResponsibilityResponse) GetGatewayExpiry() int64 {
	if x != nil {
		return x.GatewayExpiry
	}
	return 0
}

func (x *AcceptResponsibilityResponse) GetReceiptSignature() []byte {
	if x != nil {
		return x.ReceiptSignature
	}
	return nil
}

var File_sdmp_v1_transfer_proto protoreflect.FileDescriptor

const file_sdmp_v1_transfer_proto_rawDesc = "" +
	"\n" +
	"\x16sdmp/v1/transfer.proto\x12\asdmp.v1\"\x8e\x01\n" +
	"\x1bAcceptResponsibilityRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12)\n" +
	"\x10recipient_domain\x18\x02 \x01(\tR\x0frecipientDomain\x12%\n" +
	"\x0egateway_domain\x18\x03 \x01(\tR\rgatewayDomain\"\x91\x01\n" +
	"\x1cAcceptResponsibilityResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\fR\tmessageId\x12%\n" +
	"\x0egateway_expiry\x18\x02 \x01(\x03R\rgatewayExpiry\x12+\n" +
	"\x11receipt_signature\x18\x03 \x01(\fR\x10receiptSignature2v\n" +
	"\x0fTransferService\x12c\n" +
	"\x14AcceptResponsibility\x12$.sdmp.v1.AcceptResponsibilityRequest\x1a%.sdmp.v1.AcceptResponsibilityResponseB*Z(github.com/infodancer/sdmp/proto/sdmp/v1b\x06proto3"

var (
	file_sdmp_v1_transfer_proto_rawDescOnce sync.Once
	file_sdmp_v1_transfer_proto_rawDescData []byte
)

func file_sdmp_v1_transfer_proto_rawDescGZIP() []byte {
	file_sdmp_v1_transfer_proto_rawDescOnce.Do(func() {
		file_sdmp_v1_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdmp_v1_transfer_proto_rawDesc), len(file_sdmp_v1_transfer_proto_rawDesc)))
	})
	return file_sdmp_v1_transfer_proto_rawDescData
}

var file_sdmp_v1_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sdmp_v1_transfer_proto_goTypes = []any{
	(*AcceptResponsibilityRequest)(nil),  // 0: sdmp.v1.AcceptResponsibilityRequest
	(*AcceptResponsibilityResponse)(nil), // 1: sdmp.v1.AcceptResponsibilityResponse
}
var file_sdmp_v1_transfer_proto_depIdxs = []int32{
	0, // 0: sdmp.v1.TransferService.AcceptResponsibility:input_type -> sdmp.v1.AcceptResponsibilityRequest
	1, // 1: sdmp.v1.TransferService.AcceptResponsibility:output_type -> sdmp.v1.AcceptResponsibilityResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdmp_v1_transfer_proto_init() }
func file_sdmp_v1_transfer_proto_init() {
	if File_sdmp_v1_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdmp_v1_transfer_proto_rawDesc), len(file_sdmp_v1_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdmp_v1_transfer_proto_goTypes,
		DependencyIndexes: file_sdmp_v1_transfer_proto_depIdxs,
		MessageInfos:      file_sdmp_v1_transfer_proto_msgTypes,
	}.Build()
	File_sdmp_v1_transfer_proto = out.File
	file_sdmp_v1_transfer_proto_goTypes = nil
	file_sdmp_v1_transfer_proto_depIdxs = nil
}
